[workspace]
channels = ["https://prefix.dev/glatzel", "conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "linux-aarch64"]
[target.win-64.dependencies]
pkg-config = "==0.29.2"
[dependencies]
proj = "==9.7.1"
